[general]
import = [ "alacritty-local.toml", "theme.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size   = 16

[window]
opacity       = 0.9
startup_mode  = "Maximized"
option_as_alt = "OnlyLeft"
dynamic_title = false

# disable url opening
[[hints.enabled]]
command = ""
hyperlinks = true
mouse.enabled = false
