# ==== PROMPT CONFIG ====
add_newline = true
# palette = 'colors'

[palettes.dracula]
blue = '#8be9fd'
green = '#50fa7b' 
pink ='#ff79c6'
purple = '#bd93f9'
red = '#ff5555'
yellow = '#f1fa8c'

# ==== OS ====
[username]
disabled = false
show_always = false

[directory]
use_os_path_sep = false
truncation_length = 3
truncation_symbol = "…/"
style = "bold green"

# ==== [GIT] ====
[git_branch]
symbol = ' '

[git_metrics]
added_style = 'bold purple'
deleted_style = 'bold purple'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = "🏳"
up_to_date = " "
untracked = " "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = "≡"
modified = " "
staged = '[++\($count\)](green)'
renamed = "󰖷 "
deleted = " "

# ==== LANGUAGES ====
[nodejs]
symbol = '󰎙 '

[lua]
symbol = '󰢱 '

[docker_context]
symbol = '󰡨 '

[python]
symbol = '󰌠 '

[rust]
symbol = '󱘗 '

[package]
symbol = '󰏗 '

# ==== MISC ====
[cmd_duration]
disabled = false

[character]
error_symbol = "[\\$](bold red)"
success_symbol = "[\\$](bold green)"

# ==== MORE INTERESTING STUFF TO IMPLEMENT ====
# https://starship.rs/config/#battery
