# Options
format = """
$os\
$username\
$directory\
$git_branch\
$git_status\
$c\
$java\
$nodejs\
$python\
$time\
$character\
"""

add_newline = true 

# Sections
[username]
show_always = true
style_user = "fg:#262626 bg:#D8FA3B"
style_root = "fg:#262626 bg:#D8FA3B"
format = "[$user ]($style)"
disabled = false

[os]
style = "fg:#262626 bg:#D8FA3B"
format = "[░▒▓ $symbol]($style)"
disabled = false

[os.symbols]
Windows = " "
Ubuntu = " "

[directory]
style = "bg:#CF73E6"
format = "[ \ue5ff $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# git
[git_branch]
symbol = ""
style = "fg:#262626 bg:#F0D50C"
format = "[ $symbol $branch ]($style)"

[git_status]
# disable the git status if performance is bad
disabled = true
style = "fg:#262626 bg:#F0D50C"
format = "[$all_status$ahead_behind ]($style)"

# languages
[c]
style = "bg:#57BA37"
symbol = " "
format = "[ $symbol ($version) ]($style)"

[java]
style = "bg:#57BA37"
symbol = " "
format = "[ $symbol ($version) ]($style)"

[nodejs]
style = "bg:#57BA37"
symbol = ""
format = "[ $symbol ($version) ]($style)"

[python]
style = "bg:#57BA37"
symbol = ""
format = '[ $symbol (\($virtualenv\) )]($style)'
python_binary = "python3"

# Misc
[time]
disabled = false
time_format = "%R" 
style = " bg:#91AADF"
format = "[ $time ]($style)[](fg:#91AADF)"

[character]
format = " "

[line_break]
disabled = true
