# yaml-language-server: $schema=https://json.schemastore.org/lazygit.json
notARepository: skip
gui:
  nerdFontsVersion: "3"
  showBottomLine: false
  border: rounded
  mouseEvents: false
git:
  parseEmoji: true
