# yaml-language-server: $schema=https://json.schemastore.org/lazygit.json
notARepository: skip
gui:
  showIcons: true
  showBottomLine: false
  showRandomTip: false
  showCommandLog: false
  border: rounded
  mouseEvents: false
  nerdFontsVersion: "3"
git:
  parseEmoji: true
  overrideGpg: true 
customCommands:
  # credits: https://zenn.dev/glaucus03/articles/52886a4331d545
  - key: "G"
    context: "files"
    description: 'commit files with format'
    prompts:
      - type: "menu"
        title: "What kind of commit type is it?"
        key: "Type"
        options:
          - name: "✨ Feature"
            description: "Introducing new features or functionalities."
            value: ":sparkles: (feat)"

          - name: "🏗️ Refactor"
            description: "Restructuring existing code without changing its external behavior."
            value: ":building_construction: (refactor)"

          - name: "🚧 Work in progress"
            description: "Work that is in progress but not yet completed."
            value: ":construction: (wip)"

          - name: "🔧 Small tweak"
            description: "Minor adjustments or modifications."
            value: ":wrench: (tweak)"

          - name: "🎨 Code formatting"
            description: "Changes related to code formatting or style."
            value: ":art: (format)"

          - name: "🗑️ Remove code"
            description: "Removing unnecessary or unused code."
            value: ":wastebasket: (removed)"

          - name: "🐛 Bug fix"
            description: "Fixing bugs or errors in the codebase."
            value: ":bug: (bugfix)"

          - name: "🚑️ Hotfix"
            description: "Urgent fixes for critical issues in production."
            value: ":ambulance: (hotfix)"

          - name: "📝 Documentation"
            description: "Updates or additions to documentation."
            value: ":memo: (doc)"

          - name: "🧪 Test"
            description: "Adding, modifying, or improving tests."
            value: ":test_tube: (test)"

          - name: "⚡️Performance"
            description: "Improvements related to performance."
            value: ":zap: (perf)"

          - name: "💥 Breaking"
            description: "Changes that introduce breaking changes to the codebase."
            value: ":boom: (breaking)"

          - name: "⏪️ Revert changes"
            description: "Reverting previous commits or changes."
            value: ":rewind: (revert)"

          - name: "🔀 Merge"
            description: "Merging branches or pull requests."
            value: ":twisted_rightwards_arrows: (merge)"

          - name: "🏷️ Release"
            description: "Creating a new release version."
            value: ":label: (release)"

          - name: "🚀 Deploy"
            description: "Deploying changes to a production environment."
            value: ":rocket: (deploy)"

          - name: "📦️ Dependencies"
            description: "Updates or changes related to dependencies."
            value: ":package: (dep)"

          - name: "🗃️ Database"
            description: "Changes or modifications to the database schema or data."
            value: ":card_file_box: (db)"

          - name: "🌱 Seed"
            description: "Initial data setup or population for the database."
            value: ":seedling: (seed)"

          - name: "🛂 Permissions"
            description: "Changes related to access control or permissions."
            value: ":passport_control: (perms)"

          - name: "👷 CI/CD"
            description: "Changes to continuous integration or continuous deployment configurations."
            value: ":construction_worker: (ci/cd)"

          - name: "💄 UI/UX"
            description: "Improvements or changes to user interface or user experience."
            value: ":lipstick: (ui/ux)"

          - name: "🎉 New project"
            description: "Starting a new project or initializing a repository."
            value: ":tada: (start)"
      - type: "input"
        title: "Enter the commit message"
        key: "Message"
        initialValue: ""

      - type: "confirm"
        title: "Commit"
        body: "Commit with the message '{{.Form.Type}}: {{.Form.Message}}'. Is this okay?"
    command: "bash -c 'type=\"{{.Form.Type}}\"; message=\"{{.Form.Message}}\"; commit_message=\"$type: $message\"; git commit -m \"$commit_message\"'"
    loadingText: "Commiting..."
