# yaml-language-server: $schema=https://json.schemastore.org/lazygit.json
notARepository: skip
gui:
  nerdFontsVersion: "3"
  showIcons: true
  showBottomLine: false
  border: rounded
  mouseEvents: false
git:
  parseEmoji: true

customCommands:
  - key: "<c-c>"
    context: "files"
    description: 'commit files with format'
    prompts:
      - type: "menu"
        title: "What kind of commit type is it?"
        key: "Type"
        options:
          - name: "fix"
            description: "バグや不具合の修正"
            value: "fix"
          - name: "feat"
            description: "新機能の追加"
            value: "feat"
          - name: "docs"
            description: "ドキュメントの更新や改善"
            value: "docs"
          - name: "style"
            description: "コードフォーマットの修正、UIのみの変更"
            value: "style"
          - name: "refactor"
            description: "パフォーマンスの改善なしのコードの改善"
            value: "refactor"
          - name: "test"
            description: "テストの追加や改善"
            value: "test"
          - name: "perf"
            description: "パフォーマンスの改善"
            value: "perf"
          - name: "chore"
            description: "ビルドプロセスの変更や改善"
            value: "chore"
          - name: "wip"
            description: "作業中"
            value: "wip"
      - type: "input"
        title: "(Optional) Enter the scope"
        key: "Scope"
        initialValue: ""
      - type: "input"
        title: "Enter the Message"
        key: "Message"
        initialValue: ""
      - type: "menu"
        title: "Choise the emoji"
        key: "Emoji"
        options:
          - name: '(empty)'
            description: ''
            value: ''
          - name: ':ambulance:'
            description: '(fix)🚑'
            value: ':ambulance:'
          - name: ':bug:'
            description: '(fix)🐛'
            value: ':bug:'
          - name: ':+1:'
            description: '(fix)👍'
            value: ':+1:'
          - name: ':cop:'
            description: '(fix)👮'
            value: ':cop:'
          - name: ':tada'
            description: '(feat)🎉'
            value: ':tada:'
          - name: ':sparkles:'
            description: '(feat)✨'
            value: ':sparkles:'
          - name: ':up:'
            description: '(feat)🆙'
            value: ':up:'
          - name: ':memo:'
            description: '(docs)📝'
            value: ':memo:'
          - name: ':bulb'
            description: '(docs)💡'
            value: ':bulb:'
          - name: ':art:'
            description: '(style)🎨'
            value: ':art:'
          - name: ':lipstick:'
            description: '(style)💄'
            value: ':lipstick:'
          - name: ':recycle:'
            description: '(refactor)♻️ '
            value: ':recycle:'
          - name: ':fire:'
            description: '(refactor)🔥'
            value: ':fire:'
          - name: ':green_heart:'
            description: '(test)💚'
            value: ':green_heart:'
          - name: ':rocket:'
            description: '(perf)🚀'
            value: ':rocket:'
          - name: ':wrench:'
            description: '(chore)🔧'
            value: ':wrench:'
          - name: ':building_construction:'
            description: '(chore)🏗️'
            value: ':building_construction:'
          - name: ':construction:'
            description: '(wip)🚧作業中'
            value: ':construction:'
      - type: "confirm"
        title: "Commit"
        body: "Commit with the message '{{.Form.Type}}{{.Form.Scope}}: {{.Form.Message}}{{.Form.Emoji}}'. Is this okay?"
    command: "bash -c 'type=\"{{.Form.Type}}\"; scope=\"{{.Form.Scope}}\"; message=\"{{.Form.Message}}\"; emoji=\"{{.Form.Emoji}}\"; commit_message=\"$type${scope:+($scope)}: $message $emoji\"; git commit -m \"$commit_message\"'"
    loadingText: "Commiting..."
