# yaml-language-server: $schema=https://json.schemastore.org/lazygit.json
notARepository: skip
gui:
  nerdFontsVersion: "3"
  showIcons: true
  showBottomLine: false
  border: rounded
  mouseEvents: false
git:
  parseEmoji: true
customCommands:
  # credits: https://zenn.dev/glaucus03/articles/52886a4331d545
  - key: "G"
    context: "files"
    description: 'commit files with format'
    prompts:
      - type: "menu"
        title: "What kind of commit type is it?"
        key: "Type"
        options:
          - name: "✨ Feature"
            description: ""
            value: ":sparkles: (feat)"

          - name: "🏗️ Refactor"
            description: ""
            value: ":building_construction: (refactor)"

          - name: "🚧 Work in progress"
            description: ""
            value: ":construction: (wip)"

          - name: "🔧 Small tweak"
            description: ""
            value: ":wrench: (tweak)"

          - name: "🎨 Code formatting"
            description: ""
            value: ":art: (format)"

          - name: "🗑️ Remove code"
            description: ""
            value: ":wastebasket: (removed)"

          - name: "🐛 Bug fix"
            description: ""
            value: ":bug: (bugfix)"

          - name: "🚑️ Hotfix"
            description: ""
            value: ":ambulance: (hotfix)"

          - name: "📝 Documentation"
            description: ""
            value: ":memo: (doc)"

          - name: "🧪 Test"
            description: ""
            value: ":test_tube: (test)"

          - name: "⚡️Performance"
            description: ""
            value: ":zap: (perf)"

          - name: "💥 Breaking"
            description: ""
            value: ":boom: (breaking)"

          - name: "⏪️ Revert changes"
            description: ""
            value: ":rewind: (revert)"

          - name: "🔀 Merge"
            description: ""
            value: ":twisted_rightwards_arrows: (merge)"

          - name: "🏷️ Release"
            description: ""
            value: ":label: (release)"

          - name: "🚀 Deploy"
            description: ""
            value: ":rocket: (deploy)"

          - name: "📦️ Dependencies"
            description: ""
            value: ":package: (dep)"

          - name: "🗃️ Database"
            description: ""
            value: ":card_file_box: (db)"

          - name: "🌱 Seed"
            description: ""
            value: ":seedling: (seed)"

          - name: "🛂 Permissions"
            description: ""
            value: ":passport_control: (perms)"

          - name: "👷 CI/CD"
            description: ""
            value: ":construction_worker: (ci/cd)"

          - name: "💄 UI/UX"
            description: ""
            value: ":lipstick: (ui/ux)"

          - name: "🎉 New project"
            description: ""
            value: ":tada: (start)"

      - type: "input"
        title: "Enter the commit message"
        key: "Message"
        initialValue: ""

      - type: "confirm"
        title: "Commit"
        body: "Commit with the message '{{.Form.Type}}: {{.Form.Message}}'. Is this okay?"
    command: "bash -c 'type=\"{{.Form.Type}}\"; message=\"{{.Form.Message}}\"; commit_message=\"$type: $message\"; git commit -m \"$commit_message\"'"
    loadingText: "Commiting..."
