# ==== PROMPT CONFIG ====
format="""$all"""
right_format="""$aws"""
add_newline = true
# palette = 'colors'

[palettes.dracula]
blue = '#8be9fd'
green = '#50fa7b' 
pink ='#ff79c6'
purple = '#bd93f9'
red = '#ff5555'
yellow = '#f1fa8c'

# ==== OS ====
[username]
disabled = false
show_always = false

[directory]
use_os_path_sep = false
truncation_length = 3
truncation_symbol = "…/"
style = "bold green"

# ==== [GIT] ====
[git_branch]
symbol = ' '

[git_metrics]
disabled = false

[git_status]
disabled = false
# style = "bold green"
# conflicted = "🏳"
# up_to_date = " "
# untracked = " "
# ahead = "⇡${count}"
# diverged = "⇕⇡${ahead_count}⇣${behind_count}"
# behind = "⇣${count}"
# stashed = "≡"
# modified = " "
# staged = '[++\($count\)](green)'
# renamed = "󰖷 "
# deleted = " "

# ==== LANGUAGES ====
[nodejs]
symbol = '󰎙 '

[lua]
symbol = '󰢱 '

[docker_context]
symbol = '󰡨 '

[python]
symbol = '󰌠 '

[rust]
symbol = '󱘗 '

[package]
symbol = '󰏗 '


# cloud
[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
symbol = ' '

# ==== MISC ====
[cmd_duration]
disabled = false

[character]
error_symbol = "[λ](bold red)"
success_symbol = "[λ](bold green)"
vimcmd_symbol = "[λ](bold yellow)"


# ==== MORE INTERESTING STUFF TO IMPLEMENT ====
# https://starship.rs/config/#battery
