# ==== PROMPT CONFIG ====
format="""$all"""
right_format="""$container $aws $os"""
add_newline = true

# ==== OS ====
[os]
format = "on [$symbol]($style)"
style = "bold yellow"
disabled = false

[os.symbols]
Debian = " "
Windows = ' '
Arch = '󰣇'
Ubuntu = ''
Macos = '󰀵'

[username]
disabled = false
show_always = false

[directory]
use_os_path_sep = false
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
'/mnt/c/Users/' = '/Windows/'

# ==== [GIT] ====
[git_branch]
symbol = ' '

[git_metrics]
disabled = false

[git_status] # this module may be slow on windows machines
disabled = false
modified = ''
stashed = "≡"
format = '[$all_status]($style) ' 

[git_state]
style = "purple"

# ==== LANGUAGES ====
[nodejs]
format = '[$symbol ]($style)'
symbol = '󰎙 '

[lua]
format = '[$symbol ]($style)'
symbol = '󰢱 '

[docker_context]
symbol = '󰡨 '

[python]
format = '[$symbol ]($style)'
symbol = '󰌠 '

[rust]
symbol = '󱘗 '

[php]
format = '[$symbol ]($style)'
symbol = ' '

[package]
symbol = '󰏗 '

[hostname]
ssh_symbol = '󰒋 '
style = 'red'

# ==== CLOUD ====
[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
symbol = ' '

[container]
symbol = " "
style  = "cyan"

# ==== MISC ====
[character]
error_symbol = "[](red)"
success_symbol = "[](green)"
vimcmd_symbol = "[](yellow)"
