# ==== PROMPT CONFIG ====
format="""$all"""
right_format="""$aws $os"""
add_newline = true
palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

# ==== OS ====
[os]
format = "on [$symbol]($style)"
style = "bold peach"
disabled = false

[os.symbols]
Debian = " "
Windows = ' '
Arch = '󰣇'
Ubuntu = ''
Macos = '󰀵'

[username]
disabled = false
show_always = false

[directory]
use_os_path_sep = false
truncation_length = 3
truncation_symbol = "…/"
style = "yellow"

# ==== [GIT] ====
[git_branch]
symbol = ' '

[git_metrics]
disabled = false

[git_status] # this module may be slow on windows machines
disabled = false
stashed = "≡"

[git_state]
style = "bright-black"

# ==== LANGUAGES ====
[nodejs]
format = '[$symbol ]($style)'
symbol = '󰎙 '

[lua]
format = '[$symbol ]($style)'
symbol = '󰢱 '

[docker_context]
symbol = '󰡨 '

[python]
format = '[$symbol ]($style)'
symbol = '󰌠 '

[rust]
symbol = '󱘗 '

[php]
format = '[$symbol ]($style)'
symbol = ' '

[package]
symbol = '󰏗 '

[hostname]
ssh_symbol = '󰒋 '
style = 'mauve'

# ==== CLOUD ====
[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
symbol = ' '

# ==== MISC ====
[character]
error_symbol = "[](bold red)"
success_symbol = "[](bold green)"
vimcmd_symbol = "[](bold yellow)"
